export const REASONS: string[] = [
  'Because your smile turns my worst days into something beautiful.',
  'Because you listen to my silence and understand every word of it.',
  'Because you make ordinary moments feel like a movie scene.',
  'Because your laughter is the soundtrack I never want to stop hearing.',
  'Because you love me even on the days I forget to love myself.',
  'Because your eyes hold a kindness the rest of the world has forgotten.',
  'Because you turned my fear of love into a craving for more of it.',
  'Because you remember the tiny things I thought nobody noticed.',
  'Because your voice calms the storm inside my head.',
  'Because you make waiting feel like a prayer, not a punishment.',
  'Because you never ask me to be anyone other than who I am.',
  'Because your hugs feel like coming home after a long war.',
  'Because you make me want to be a better man, quietly, every day.',
  'Because even your anger is wrapped in care for me.',
  'Because you make the stars feel a little less far away.',
  'Because you taught my heart a language it never knew before.',
  'Because you are my favourite hello and my hardest goodbye.',
  'Because your dreams somehow always include me in them.',
  'Because you cry at little things, and that makes you beautiful.',
  'Because you fight for us even when you are tired of fighting.',
  'Because your hand in mine feels like the safest place on earth.',
  'Because you make playlists that say the things you cannot.',
  'Because you forgive me faster than I deserve.',
  'Because you see my scars and call them stories of strength.',
  'Because you make me believe in forever without ever saying the word.',
  'Because your "good morning" is the only alarm I want to wake up to.',
  'Because you make me laugh at jokes only we understand.',
  'Because you hold my hope when my hands are too tired to.',
  'Because you never make me feel small for being afraid.',
  'Because your patience is the quiet kind of love that never gives up.',
  'Because you turned my loneliness into a memory.',
  'Because you make rain feel romantic instead of sad.',
  'Because you send me your voice notes like little pieces of your heart.',
  'Because you believe in me even when the evidence says otherwise.',
  'Because you make distance feel like a bridge, not a wall.',
  'Because you celebrate my tiny wins like they are championships.',
  'Because you never let me go to sleep feeling unloved.',
  'Because you make me want to write, and I never liked writing.',
  'Because your stubbornness reminds me you will never let go.',
  'Because you make every festival brighter just by existing.',
  'Because you love my people like they are your own.',
  'Because you make me want to come back home, every single time.',
  'Because you understand my mood from the way I text "ok".',
  'Because you make me dream bigger so I can give you more.',
  'Because you never count what you do for me, you just keep doing it.',
  'Because you make my name sound like a song when you say it.',
  'Because you are the first person I want to tell everything to.',
  'Because you make me believe that soulmates are real.',
  'Because you carry my worries like they weigh nothing.',
  'Because you make my restless heart finally sit still.',
  'Because you love with your whole self, no halves, no maybes.',
  'Because you make me want to protect you from everything, even the wind.',
  'Because you make my future feel like a person, not a plan.',
  'Because you turn my overthinking into a quiet "it\'s okay, I\'m here".',
  'Because you make me want to grow old just to love you longer.',
  'Because you never make me feel like I am too much.',
  'Because you make me brave when all I want to do is hide.',
  'Because you are the reason my poems stopped being sad.',
  'Because you make my heart beat in a rhythm only you can hear.',
  'Because you stay, even when staying is the harder choice.',
  'Because you make the dark feel like a place we can rest together.',
  'Because you make me want to be remembered, by you, always.',
  'Because you hold my heart like it is made of glass and gold.',
  'Because you make me feel chosen, not just loved.',
  'Because you are my favourite story to tell, over and over.',
  'Because you make me believe I deserve the love I give.',
  'Because you make every photograph feel like a memory worth keeping.',
  'Because you never let a fight end without fixing us.',
  'Because you make me want to wake up early, just to talk to you.',
  'Because you make my tiredness disappear with a single "paaru".',
  'Because you love my messy, not just my best.',
  'Because you make me want to learn every love language there is.',
  'Because you are the calm my anxious heart has been searching for.',
  'Because you make me proud of the man I am becoming.',
  'Because you make me want to fight the world, not with it.',
  'Because you make my heart softer and my spine stronger at once.',
  'Because you make me believe that waiting has a beautiful ending.',
  'Because you make every "I miss you" feel like a promise to return.',
  'Because you love me in a way that makes me love myself.',
  'Because you make my heart feel full even when my hands are empty.',
  'Because you are the reason I believe in beginnings.',
  'Because you make me want to be remembered as someone who loved you well.',
  'Because you make my silence feel understood, not empty.',
  'Because you turn my doubts into quiet, steady faith.',
  'Because you make me feel like the luckiest, even on unlucky days.',
  'Because you make me want to build a life, not just live one.',
  'Because you make my heart feel like it finally fits where it belongs.',
  'Because you never make me doubt that I am yours.',
  'Because you make me want to write your name on everything I create.',
  'Because you make every goodbye feel temporary and every hello feel eternal.',
  'Because you make my dreams feel like plans instead of wishes.',
  'Because you love me in the morning, before the world has been kind to me.',
  'Because you make me want to be the man you point to and say "that\'s him".',
  'Because you make my heart believe in forever without needing proof.',
  'Because you make me want to be patient, because you are worth the wait.',
  'Because you make every road, every city, every moment feel like ours.',
  'Because you make me want to protect your smile with my whole life.',
  'Because you make me believe that love, real love, never leaves.',
  'Because you are the answer to every prayer I never knew how to say.',
  'Because you make me want to hold your hand forever and never let go.',
  'Because you make me feel like I finally found the one my soul was looking for.',
  'Because you make me want to give you the whole world, one day at a time.',
  'Because you are, and will always be, my favourite reason to live and to love.',
];
